include:
  - compose.resources.yaml

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      valkey:
        condition: service_started
